### ISSUE TITLE
The system skin does not work

### ISSUE THREAD

**Issue by ChinmayMR** [Robzyy/Rainmeter-addons#1]
The system skin you gave just shows up like [this ](https://imgur.com/a/0qUyPrL)there is text instead of the icons. I'd love some help 
Thank you

**Comment by Robzyy** [comment]
The repo's wiki shows how to properly set up the skin. Make sure you follow
it.

**Comment by ChinmayMR** [comment]
I have installed the Isoveska font

**Comment by Robzyy** [comment]
Give this a read: https://github.com/Robzyy/Rainmeter-addons/wiki/CakeOS.

**Comment by ChinmayMR** [comment]
Thank you will try it out later
